# Generated by Django 3.1.7 on 2021-03-31 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='MetroStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('line', models.IntegerField()),
                ('latitude', models.DecimalField(decimal_places=22, max_digits=25)),
                ('longitude', models.DecimalField(decimal_places=22, max_digits=25)),
            ],
            options={
                'db_table': 'metro_stations',
            },
        ),
        migrations.CreateModel(
            name='OpenStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': 'open_status',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('one_line_introduction', models.CharField(max_length=100, null=True)),
                ('opening_time_description', models.CharField(max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('sns_url', models.CharField(max_length=500, null=True)),
                ('menu_pamphlet_image_url', models.CharField(max_length=3000, null=True)),
                ('is_reservation', models.BooleanField(default=True)),
                ('is_wifi', models.BooleanField(default=True)),
                ('is_parking', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category')),
                ('open_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.openstatus')),
            ],
            options={
                'db_table': 'stores',
            },
        ),
        migrations.CreateModel(
            name='StoreImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=3000)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.store')),
            ],
            options={
                'db_table': 'store_images',
            },
        ),
        migrations.CreateModel(
            name='MetroStationStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metro_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.metrostation')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.store')),
            ],
            options={
                'db_table': 'metro_stations_stores',
            },
        ),
        migrations.AddField(
            model_name='metrostation',
            name='near_store',
            field=models.ManyToManyField(through='store.MetroStationStore', to='store.Store'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=22, max_digits=25)),
                ('longitude', models.DecimalField(decimal_places=22, max_digits=25)),
                ('full_address', models.CharField(max_length=200)),
                ('region_1depth_name', models.CharField(max_length=30)),
                ('region_2depth_name', models.CharField(max_length=30)),
                ('region_3depth_name', models.CharField(max_length=30)),
                ('road_name', models.CharField(max_length=30)),
                ('building_name', models.CharField(max_length=30)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.store')),
            ],
            options={
                'db_table': 'addresses',
            },
        ),
        migrations.AlterUniqueTogether(
            name='metrostation',
            unique_together={('name', 'line')},
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('menu_image_url', models.CharField(max_length=3000, null=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.store')),
            ],
            options={
                'db_table': 'menus',
                'unique_together': {('store', 'name')},
            },
        ),
    ]
