# Generated by Django 3.1.7 on 2021-04-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210331_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='building_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='metrostation',
            name='line',
            field=models.CharField(max_length=30),
        ),
    ]
