# Generated by Django 3.1.7 on 2021-04-04 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image_url',
            field=models.CharField(max_length=3000, null=True),
        ),
    ]
